apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: {{ .Values.redis.name }}-service
    app: {{ .Values.global.label.app }}
spec:
  ports:
    - port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
  selector:
    name: {{ .Values.redis.name }}-pod
    app: {{ .Values.global.label.app }}
