apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.result.name }}-deploy
  labels:
    name: {{ .Values.result.name }}-deploy
    app: {{ .Values.global.label.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.result.name }}-pod
      app: {{ .Values.global.label.app }}
  template:
    metadata:
      name: {{ .Values.result.name }}-pod
      labels:
        name: {{ .Values.result.name }}-pod
        app: {{ .Values.global.label.app }}
    spec:
      containers:
        - name: {{ .Values.result.name }}
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
