apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: {{ .Values.global.label.app }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: {{ .Values.voting.name}}-pod
    app: {{ .Values.global.label.app }}
