apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: {{ .Values.global.label.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: {{ .Values.global.label.app }}
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: {{ .Values.global.label.app }}
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1

